
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: streamjs
  namespace: streaming
  labels:
    app: streamjs
spec:
  serviceName: "streamjs"
  replicas: 2
  selector:
    matchLabels:
      app: streamjs
  template:
    metadata:
      labels:
        app: streamjs
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      containers:
      - name: streamjs
        image: devjyk/streamjs:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 512Mi 
          requests:
            cpu: 250m
            memory: 256Mi
        env:
        - name: KAFKA_CLIENT_ID
          value: "streamjs"
        - name: KAFKA_BROKERS
          value: "kafka-kafka-bootstrap.streaming.svc.cluster.local:9092"
        livenessProbe:
          httpGet:
            path: /ping
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ping
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 30