{
 "title": "Kafka Metrics Dashboard 2",
 "tags": [ "kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "kafka_client",
    "query": {
     "query": "label_values(kafka_producer_connection_count, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kafka Producer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Producer Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(rate(kafka_producer_request_total{name=~\"$kafka_client\"}[5m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Request Duration (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafka_producer_request_duration_seconds_bucket{name=~\"$kafka_client\"}[5m])) by (le, name))",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  { "title": "Kafka Consumer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Consumer Fetch Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(rate(kafka_consumer_fetch_total{name=~\"$kafka_client\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Consumer Fetch Latency (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kafka_consumer_fetch_latency_bucket{name=~\"$kafka_client\"}[5m])) by (le, name))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}